### ISSUE TITLE
MST / PrivBayes fail when a (categorical) value does *not* appear in the data.

### ISSUE THREAD

**Issue by fhoussiau** [alan-turing-institute/reprosyn#47]
The post-processing step with the following message (log from my machine, with a run from `prive`). This is probably a `mst` specific bug rather than `reprosyn`, but I haven't had the time to check.

```
Traceback (most recent call last):
  File "/Users/fhoussiau/workspace/privacy-sdg-toolbox/own-research/paper/experiment_mia.py", line 121, in <module>
    threat_model._generate_samples(num_samples=num_training, training=True)
  File "/Users/fhoussiau/workspace/privacy-sdg-toolbox/prive/threat_models/attacker_knowledge.py", line 385, in _generate_samples
    gen_datasets = [
  File "/Users/fhoussiau/workspace/privacy-sdg-toolbox/prive/threat_models/attacker_knowledge.py", line 386, in <listcomp>
    self.atk_know_gen(ds) for ds in self.iterator_tracker(training_datasets)
  File "/Users/fhoussiau/workspace/privacy-sdg-toolbox/prive/threat_models/attacker_knowledge.py", line 234, in __call__
    return self.generate(training_dataset)
  File "/Users/fhoussiau/workspace/privacy-sdg-toolbox/prive/threat_models/attacker_knowledge.py", line 258, in generate
    return self.generator(training_dataset, self.num_synthetic_records)
  File "/Users/fhoussiau/workspace/privacy-sdg-toolbox/prive/generators/generator.py", line 30, in __call__
    return self.generate(num_samples)
  File "/Users/fhoussiau/workspace/privacy-sdg-toolbox/own-research/paper/experiment_mia.py", line 34, in generate
    model.run()
  File "/Users/fhoussiau/Library/Caches/pypoetry/virtualenvs/prive-Lu1J6cTh-py3.9/lib/python3.9/site-packages/reprosyn/generator.py", line 82, in run
    self.postprocess()
  File "/Users/fhoussiau/Library/Caches/pypoetry/virtualenvs/prive-Lu1J6cTh-py3.9/lib/python3.9/site-packages/reprosyn/methods/mbi/privbayes.py", line 140, in postprocess
    self.output = recode_as_original(self.output.df, self.mapping)
  File "/Users/fhoussiau/Library/Caches/pypoetry/virtualenvs/prive-Lu1J6cTh-py3.9/lib/python3.9/site-packages/reprosyn/generator.py", line 165, in recode_as_original
    data[col] = data[col].apply(lambda x: mapping[col][x])
  File "/Users/fhoussiau/Library/Caches/pypoetry/virtualenvs/prive-Lu1J6cTh-py3.9/lib/python3.9/site-packages/pandas/core/series.py", line 4433, in apply
    return SeriesApply(self, func, convert_dtype, args, kwargs).apply()
  File "/Users/fhoussiau/Library/Caches/pypoetry/virtualenvs/prive-Lu1J6cTh-py3.9/lib/python3.9/site-packages/pandas/core/apply.py", line 1088, in apply
    return self.apply_standard()
  File "/Users/fhoussiau/Library/Caches/pypoetry/virtualenvs/prive-Lu1J6cTh-py3.9/lib/python3.9/site-packages/pandas/core/apply.py", line 1143, in apply_standard
    mapped = lib.map_infer(
  File "pandas/_libs/lib.pyx", line 2870, in pandas._libs.lib.map_infer
  File "/Users/fhoussiau/Library/Caches/pypoetry/virtualenvs/prive-Lu1J6cTh-py3.9/lib/python3.9/site-packages/reprosyn/generator.py", line 165, in <lambda>
    data[col] = data[col].apply(lambda x: mapping[col][x])
KeyError: 2
```

**Comment by fhoussiau** [comment]
Actually this error occurs in the test notebook at https://github.com/alan-turing-institute/reprosyn/blob/main/examples/reprosyn_as_package.ipynb

**Comment by fhoussiau** [comment]
I have produced a simple example (using `prive` to load the data) that produces this error.

```
from reprosyn.methods import MST
import prive.datasets

data = prive.datasets.TabularDataset.read("path/to/census_and_json")
data = data.sample(5)
model = MST(dataset=data.data, metadata=data.description, size=100)
model.run()
```
